OroCRM\Bundle\ContactBundle\Entity\Contact:
    icon_class:                         icon-user
    name:                               orocrm.contact.entity_label
    description:                        orocrm.contact.entity_description

OroCRM\Bundle\ContactBundle\Entity\ContactAddress:
    name:                               orocrm.contact.contactaddress.entity_label
    description:                        orocrm.contact.contactaddress.entity_description

OroCRM\Bundle\ContactBundle\Entity\Group:
    name:                               orocrm.contact.group.entity_label
    description:                        orocrm.contact.group.entity_description
