datagrid:
    orocrm_report-accounts-life_time_value:
        pageTitle: "Account life time value"
        source:
            type: orm
            acl_resource: oro_report_view
            query:
                select:
                    - a.id
                    - a.name
                    - SUM( o.closeRevenue ) as value
                from:
                    - { table: OroCRMSalesBundle:Opportunity, alias: o }
                join:
                    inner:
                        - { join: o.account, alias: a }
                        - { join: o.status,  alias: s }
                where:
                    and:
                        - s.name = 'won'
                groupBy:  a.id
        columns:
            name:   { label: orocrm.report.datagrid.columns.account_name }
            value:  { label: orocrm.report.datagrid.columns.total_value,  frontend_type: currency }
        properties:
            id: ~
        totals:
            total:
                extends: grand_total
                per_page: true
                hide_if_one_page: true
                columns:
                    name:
                        label: 'Page total'

            grand_total:
                columns:
                    name:
                        label: 'Grand Total'
                    value:
                        expr: SUM( o.closeRevenue )
                        formatter: currency
        sorters:
            columns:
                name:   { data_name: a.name }
                value:  { data_name: value }
        filters:
            columns:
                name:
                    type: string
                    data_name: a.name
                value:
                    type:             number
                    data_name:        value
                    filter_by_having: true
                    options:
                        data_type:    Oro\Bundle\FilterBundle\Form\Type\Filter\NumberFilterType::DATA_DECIMAL
                closeDate:
                    type:             date
                    label:            orocrm.report.datagrid.columns.close_date
                    data_name:        o.closeDate
                createdAt:
                    type:             date
                    label:            orocrm.report.datagrid.columns.created_date
                    data_name:        o.createdAt
        options:
            entityHint: report data
            export: true

    orocrm_report-accounts-by_opportunities:
        pageTitle: "Accounts by opportunities"
        source:
            type: orm
            acl_resource: oro_report_view
            query:
                from:
                    - { table: OroCRMSalesBundle:Opportunity, alias: o }
                select:
                    - a.id
                    - a.name
                    - SUM( (CASE WHEN (s.name='won') THEN 1 ELSE 0 END) ) as wonCount
                    - SUM( (CASE WHEN (s.name='lost') THEN 1 ELSE 0 END) ) as lostCount
                    - SUM( (CASE WHEN (s.name='in_progress') THEN 1 ELSE 0 END) ) as inProgressCount
                    - COUNT(o.id) as totalOps
                join:
                    inner:
                        - { join: o.account, alias: a }
                        - { join: o.status, alias: s }
                groupBy:  a.id
        properties:
            id: ~
        totals:
            total:
                extends: grand_total
                per_page: true
                hide_if_one_page: true
                columns:
                    name:
                        label: 'Page Total'
            grand_total:
                columns:
                    name:
                        label: 'Grand Total'
                    wonCount:
                        expr: SUM( (CASE WHEN (s.name='won') THEN 1 ELSE 0 END) )
                    lostCount:
                        expr: SUM( (CASE WHEN (s.name='lost') THEN 1 ELSE 0 END) )
                    inProgressCount:
                        expr: SUM( (CASE WHEN (s.name='in_progress') THEN 1 ELSE 0 END) )
                    totalOps:
                        expr: COUNT(o.id)
        columns:
            name:             { label: orocrm.report.datagrid.columns.account_name }
            wonCount:         { label: orocrm.report.datagrid.columns.wonCount,  frontend_type: integer }
            lostCount:        { label: orocrm.report.datagrid.columns.lostCount,  frontend_type: integer }
            inProgressCount:  { label: orocrm.report.datagrid.columns.inProgressCount,  frontend_type: integer }
            totalOps:         { label: orocrm.report.datagrid.columns.totalOps,  frontend_type: integer }
        sorters:
            columns:
                name:              { data_name: a.name }
                wonCount:          { data_name: wonCount }
                lostCount:         { data_name: lostCount }
                inProgressCount:   { data_name: inProgressCount }
                totalOps:          { data_name: totalOps }
        filters:
            columns:
                name:
                    type:        string
                    data_name:   a.name
                wonCount:
                    type:        number
                    data_name:   wonCount
                    filter_by_having: true
                lostCount:
                    type:        number
                    data_name:   lostCount
                    filter_by_having: true
                inProgressCount:
                    type:        number
                    data_name:   inProgressCount
                    filter_by_having: true
                totalOps:
                    type:        number
                    data_name:   totalOps
                    filter_by_having: true
                closeDate:
                    type:        date
                    label:       orocrm.report.datagrid.columns.close_date
                    data_name:   o.closeDate
                createdAt:
                    type:        date
                    label:       orocrm.report.datagrid.columns.created_date
                    data_name:   o.createdAt
        options:
            entityHint: report data
            export: true

    orocrm_report-leads-by_date:
        pageTitle: "Number leads by date"
        source:
            type: orm
            acl_resource: oro_report_view
            query:
                select:
                    - COUNT(l.id) as leadsCount
                    - SUBSTRING(l.createdAt, 1, 10) as createdDate
                from:
                    - { table: OroCRMSalesBundle:Lead, alias: l }
                groupBy: createdDate
        totals:
            total:
                extends: grand_total
                per_page: true
                hide_if_one_page: true
                columns:
                    createdDate:
                        label: 'Page Total'
            grand_total:
                columns:
                    createdDate:
                        label: 'Grand Total'
                    leadsCount:
                        expr: COUNT(l.id)
        columns:
            createdDate:    { label: orocrm.report.datagrid.columns.created_date, frontend_type: date }
            leadsCount:     { label: orocrm.report.datagrid.columns.leads_count,  frontend_type: integer }
        sorters:
            columns:
                createdDate:   { data_name: createdDate }
                leadsCount:    { data_name: leadsCount }
        filters:
            columns:
                createdDate:   { type: date, data_name: createdDate, filter_by_having: true }
                leadsCount:    { type: number, data_name: leadsCount, filter_by_having: true }
        options:
            entityHint: report data
            export: true

    orocrm_report-opportunities-by_status:
        pageTitle: "Opportunities by status"
        source:
            type: orm
            acl_resource: oro_report_view
            query:
                from:
                    - { table: OroCRMSalesBundle:Opportunity, alias: opportunity }
                join:
                    inner:
                        - { join: opportunity.status, alias: status }
                select:
                    - status.label as statusLabel
                    - COUNT(opportunity.id) as numberOfOpportunities
                    - >
                      SUM(
                        CASE WHEN status.name IN ('won', 'lost') THEN opportunity.closeRevenue ELSE 0 END
                      ) as closeRevenue
                    - >
                      SUM(
                        CASE WHEN opportunity.budgetAmount IS NOT NULL THEN opportunity.budgetAmount ELSE 0 END
                      ) as budgetAmount
                groupBy: statusLabel
        totals:
            total:
                extends: grand_total
                per_page: true
                hide_if_one_page: true
                columns:
                    statusLabel:
                        label: 'Page Total'
            grand_total:
                columns:
                    statusLabel:
                        label: 'Grand Total'
                    numberOfOpportunities:
                        expr: COUNT(opportunity.id)
                    closeRevenue:
                        expr: SUM(CASE WHEN status.name IN ('won', 'lost') THEN opportunity.closeRevenue ELSE 0 END)
                        formatter: currency
                    budgetAmount:
                        expr: SUM(CASE WHEN opportunity.budgetAmount IS NOT NULL THEN opportunity.budgetAmount ELSE 0 END)
                        formatter: currency
        columns:
            statusLabel:           { label: orocrm.report.datagrid.columns.status }
            numberOfOpportunities: { label: orocrm.report.datagrid.columns.number_of_opportunities, frontend_type: integer }
            closeRevenue:          { label: orocrm.report.datagrid.columns.close_revenue, frontend_type: currency }
            budgetAmount:          { label: orocrm.report.datagrid.columns.budget_amount, frontend_type: currency }
        sorters:
            columns:
                statusLabel:           { data_name: statusLabel }
                numberOfOpportunities: { data_name: numberOfOpportunities }
                closeRevenue:          { data_name: closeRevenue }
                budgetAmount:          { data_name: budgetAmount }
        filters:
            columns:
                statusLabel:
                    type: entity
                    data_name: opportunity.status
                    options:
                        field_options:
                            class: OroCRMSalesBundle:OpportunityStatus
                            property: label
                numberOfOpportunities:
                    type: number
                    data_name: numberOfOpportunities
                    filter_by_having: true
                closeRevenue:
                    type: number
                    data_name: closeRevenue
                    filter_by_having: true
                    options:
                        data_type:    Oro\Bundle\FilterBundle\Form\Type\Filter\NumberFilterType::DATA_DECIMAL
                budgetAmount:
                    type: number
                    data_name: budgetAmount
                    filter_by_having: true
                    options:
                        data_type:    Oro\Bundle\FilterBundle\Form\Type\Filter\NumberFilterType::DATA_DECIMAL
        options:
            entityHint: report data
            export: true

    orocrm_report-opportunities-won_by_period:
        pageTitle: "Won opportunities by date period"
        source:
            type: orm
            acl_resource: oro_report_view
            query:
                from:
                    - { table: OroCRMSalesBundle:Opportunity, alias: o }
                select:
                    - CONCAT( CONCAT( SUBSTRING( o.closeDate, 6, 2 ), ' / '), SUBSTRING( o.closeDate, 1, 4 ) ) as monthPeriod
                    - >
                      CONCAT(
                        CASE
                          WHEN SUBSTRING(o.closeDate, 6, 2) BETWEEN 1 AND 3 THEN '1'
                          WHEN SUBSTRING(o.closeDate, 6, 2) BETWEEN 4 AND 6 THEN '2'
                          WHEN SUBSTRING(o.closeDate, 6, 2) BETWEEN 7 AND 9 THEN '3'
                          ELSE '4'
                        END,
                        CONCAT(
                          ' / ',
                          SUBSTRING( o.closeDate, 1, 4 )
                        )
                      ) as quarterPeriod
                    - SUBSTRING( o.closeDate, 1, 4 ) as yearPeriod
                    - SUM( o.closeRevenue ) as value
                    - COUNT( o.id ) as cnt
                join:
                    inner:
                        - { join: o.status, alias: s }
                where:
                    and:
                        - s.name = 'won'
                        - o.closeDate IS NOT NULL
        properties:
            monthPeriod: ~
            quarterPeriod: ~
            yearPeriod: ~
        totals:
            total:
                extends: grand_total
                per_page: true
                hide_if_one_page: true
                columns:
                    period:
                        label: 'Page Total'
            grand_total:
                columns:
                    period:
                        label: 'Grand Total'
                    cnt:
                        expr: COUNT( o.id )
                    value:
                        expr: SUM( o.closeRevenue )
                        formatter: currency

        columns:
            period:    { label: orocrm.report.datagrid.columns.period }
            cnt:       { label: orocrm.report.datagrid.columns.number_won, frontend_type: integer }
            value:     { label: orocrm.report.datagrid.columns.total_value, frontend_type: currency }
        sorters:
            columns:
                period:     { data_name: period }
                cnt:        { data_name: cnt }
                value:      { data_name: value }
        filters:
            columns:
                period:
                    type: orocrm_period_filter
                    data_name: period
                    options:
                        populate_default: false
                        field_options:
                            choices:
                                monthPeriod:    Monthly
                                quarterPeriod:  Quarterly
                                yearPeriod:     Yearly
                cnt:
                    type: number
                    data_name: cnt
                    filter_by_having: true
                value:
                    type: number
                    data_name: value
                    filter_by_having: true
                    options:
                        data_type:    Oro\Bundle\FilterBundle\Form\Type\Filter\NumberFilterType::DATA_DECIMAL
                closeDate:
                    type:        date
                    label:       orocrm.report.datagrid.columns.close_date
                    data_name:   o.closeDate
                createdAt:
                    type:        date
                    label:       orocrm.report.datagrid.columns.created_date
                    data_name:   o.createdAt
            default:
                period: { value: monthPeriod }
        options:
            entityHint: report data
            export: true
