orocrm_call_bundle:
    resource: "@OroCRMCallBundle/Controller"
    type:     annotation
    prefix:   /call

orocrm_call_api:
    resource: "@OroCRMCallBundle/Controller/Api/Rest/CallController.php"
    type:     rest
    prefix:       api/rest/{version}/
    requirements:
        version:  latest|v1
    defaults:
        version:  latest