workflows:
    b2c_flow_abandoned_shopping_cart:
        steps:
            open:
                label: 'Open'
                order: 10
                allowed_transitions:
                    - log_call
                    - send_email
                    - convert_to_opportunity
            contacted:
                label: 'Contacted'
                order: 20
                allowed_transitions:
                    - log_call
                    - send_email
                    - convert
                    - convert_to_opportunity
                    - abandon
            abandoned:
                label: 'Abandoned'
                order: 30
                allowed_transitions:
                    - reopen
                is_final: true
            converted_to_opportunity:
                label: 'Converted to opportunity'
                order: 30
                allowed_transitions:
                    - reopen
                is_final: true
            converted:
                label: 'Converted'
                order: 30
                allowed_transitions:
                    - reopen
                is_final: true
