parameters:
    sweettooth_binding.binding_synchronizer.class:                      SweetTooth\Bundle\BindingBundle\Sync\BindingSynchronizer

    # Listeners
    sweettooth_binding.contact.post_persist_listener.class:             SweetTooth\Bundle\BindingBundle\Entity\Listener\ContactPostPersist
    sweettooth_binding.magento_order.post_persist_listener.class:       SweetTooth\Bundle\BindingBundle\Entity\Listener\MagentoOrderPostPersist

services:
    # Synchronizers
    sweettooth_binding.binding_synchronizer:
        scope: prototype
        class: %sweettooth_binding.binding_synchronizer.class%
        arguments:
            - @doctrine.orm.entity_manager
        calls:
            - [ setContainer, [ @service_container ] ]

    # Listeners
    sweettooth_binding.contact.post_persist_listener:
        class: %sweettooth_binding.contact.post_persist_listener.class%
        arguments:
            - @service_container
        tags:
            - { name: doctrine.event_listener, event: postPersist }
            - { name: doctrine.event_listener, event: postUpdate }

    sweettooth_binding.magento_order.post_persist_listener:
        class: %sweettooth_binding.magento_order.post_persist_listener.class%
        tags:
            - { name: doctrine.event_listener, event: postPersist }
            - { name: doctrine.event_listener, event: postUpdate }

    # Brokers
    sweettooth_binding.contact_broker:
        class: SweetTooth\Bundle\BindingBundle\Broker\ContactBroker
        arguments:
            - @doctrine.orm.entity_manager
            - @service_container

    sweettooth_binding.magento_order_broker:
        class: SweetTooth\Bundle\BindingBundle\Broker\MagentoOrderBroker
        arguments:
            - @doctrine.orm.entity_manager
            - @service_container
