datagrid:
    dashboard-my-accounts-activity-grid:
        source:
            type: orm
            acl_resource: orocrm_account_view
            query:
                select:
                    - a.id
                    - a.name
                    - defaultContactEmail.email as contactEmail
                    - defaultContactPhone.phone as contactPhone
                    - max(history.visitedAt) as visitDate
                from:
                    - { table: %orocrm_account.account.entity.class%, alias: a }
                join:
                    left:
                        - { join: a.defaultContact, alias: defaultContact }
                        - { join: defaultContact.emails, alias: defaultContactEmail, conditionType: 'WITH', condition: 'defaultContactEmail.primary = true' }
                        - { join: defaultContact.phones, alias: defaultContactPhone, conditionType: 'WITH', condition: 'defaultContactPhone.primary = true' }
                    inner:
                        -
                            join: Oro\Bundle\NavigationBundle\Entity\NavigationHistoryItem
                            alias: history
                            conditionType: WITH
                            condition: "a.id = substring(history.url, locate('/', history.url, locate('/account/', history.url) + 9) + 1)"
                where:
                    and:
                      - locate('/account/', history.url) <> 0
                      - history.user = @oro_security.security_facade->getLoggedUserId
                groupBy:  a.id, a.name, contactEmail, contactPhone
        sorters:
            visitDate: { history.: %oro_datagrid.extension.orm_sorter.class%::DIRECTION_DESC }
        columns:
            name:
                type: twig
                label: orocrm.account.name.label
                frontend_type: html
                template: OroCRMAccountBundle:Account:Datagrid/Property/accountName.html.twig
            contactEmail:
                label: orocrm.contact.contactemail.email.label
            contactPhone:
                label: orocrm.contact.contactphone.phone.label
        options:
            entityHint: account
            toolbarOptions:
                hide: true
                pageSize:
                    items: [10]
                    default_per_page: 10

    accounts-grid:
        extended_entity_name: %orocrm_account.account.entity.class%
        source:
            type:           orm
            acl_resource:   orocrm_account_view
            query:
                select:
                    - a.id
                    - a.name
                    - a.createdAt
                    - a.updatedAt
                    - CONCAT(defaultContact.firstName, CONCAT(' ', defaultContact.lastName)) as contactName
                    - defaultContactEmail.email as contactEmail
                    - defaultContactPhone.phone as contactPhone
                    - CONCAT(accountOwner.firstName, CONCAT(' ', accountOwner.lastName)) as ownerName
                from:
                    - { table: %orocrm_account.account.entity.class%, alias: a }
                join:
                    left:
                        - { join: a.defaultContact, alias: defaultContact }
                        - { join: defaultContact.emails, alias: defaultContactEmail, conditionType: 'WITH', condition: 'defaultContactEmail.primary = true' }
                        - { join: defaultContact.phones, alias: defaultContactPhone, conditionType: 'WITH', condition: 'defaultContactPhone.primary = true' }
                        - { join: a.owner, alias: accountOwner }
        properties:
            id: ~
            view_link:
                type:       url
                route:      orocrm_account_view
                params:     [ id ]
            update_link:
                type:       url
                route:      orocrm_account_update
                params:     [ id ]
            delete_link:
                type:       url
                route:      oro_api_delete_account
                params:     [ id ]
        columns:
            name:
                label:   orocrm.account.name.label
            contactName:
                label:   orocrm.account.contact.name
            contactEmail:
                label:   orocrm.account.contact.email
            contactPhone:
                label:   orocrm.account.contact.phone
            ownerName:
                label:   orocrm.account.owner.label
            createdAt:
                label:   orocrm.account.created_at.label
                frontend_type: datetime
            updatedAt:
                label:   orocrm.account.updated_at.label
                frontend_type: datetime
        sorters:
            columns:
                name:
                    data_name: a.name
                contactName:
                    data_name: contactName
                contactEmail:
                    data_name: contactEmail
                contactPhone:
                    data_name: contactPhone
                ownerName:
                    data_name: ownerName
                createdAt:
                    data_name: a.createdAt
                updatedAt:
                    data_name: a.updatedAt
        filters:
            columns:
                name:
                    type:      string
                    data_name: a.name
                contactName:
                    type:      string
                    data_name: contactName
                contactEmail:
                    type:      string
                    data_name: contactEmail
                contactPhone:
                    type:      string
                    data_name: contactPhone
                ownerName:
                    type:      string
                    data_name: ownerName
                createdAt:
                    type:      datetime
                    data_name: a.createdAt
                updatedAt:
                    type:      datetime
                    data_name: a.updatedAt
        actions:
            view:
                type:          navigate
                acl_resource:  orocrm_account_view
                label:         View
                icon:          user
                link:          view_link
                rowAction:     true
            update:
                type:          navigate
                acl_resource:  orocrm_account_update
                label:         Update
                icon:          edit
                link:          update_link
            delete:
                type:          delete
                acl_resource:  orocrm_account_delete
                label:         Delete
                icon:          trash
                link:          delete_link
        mass_actions:
            merge:
                type: merge
                entity_name: %orocrm_account.account.entity.class%
                data_identifier: a.id
        options:
            entityHint: account
            export: true

    base-account-contacts-grid:
        extended_entity_name: %orocrm_contact.entity.class%
        source:
            type: orm
            acl_resource: orocrm_contact_view
            query:
                select:
                    # selects full entity because group labels should be taken from object
                    - c
                    - contactSource.label as contactSourceLabel
                    - email.email as primaryEmail
                    - phone.phone as primaryPhone
                    - CONCAT(CASE WHEN address.regionText IS NOT NULL THEN address.regionText ELSE region.name END, '') as regionLabel
                    - country.name as countryName
                    - address.postalCode as addressPostalCode
                from:
                    - { table: %orocrm_contact.entity.class%, alias: c }
                join:
                    left:
                        - { join: c.addresses, alias: address, conditionType: WITH, condition: 'address.primary = true' }
                        - { join: c.emails, alias: email, conditionType: WITH, condition: 'email.primary = true' }
                        - { join: c.phones, alias: phone, conditionType: WITH, condition: 'phone.primary = true' }
                        - { join: c.groups, alias: contactGroup }
                        - { join: c.source, alias: contactSource }
                        - { join: address.country, alias: country }
                        - { join: address.region, alias: region }
        sorters:
            columns:
                first_name:
                    data_name: c.firstName
                last_name:
                    data_name: c.lastName
                primaryEmail:
                    data_name: email.email
                primaryPhone:
                    data_name: phone.phone
                countryName:
                    data_name: country.name
                regionLabel:
                    data_name: regionLabel
                addressPostalCode:
                    data_name: address.postalCode
            default:
                lastName: ASC
        options:
            entityHint: contact

    account-contacts-update-grid:
        extends: base-account-contacts-grid
        source:
            query:
                select:
                    - >
                        (CASE WHEN (:account IS NOT NULL) THEN
                          CASE WHEN (:account MEMBER OF c.accounts OR c.id IN (:data_in)) AND c.id NOT IN (:data_not_in)
                          THEN true ELSE false END
                        ELSE
                          CASE WHEN c.id IN (:data_in) AND c.id NOT IN (:data_not_in)
                          THEN true ELSE false END
                        END) as hasContact
        columns:
            hasContact:
                label:   Assigned
                editable: true
                frontend_type: boolean
            first_name:
                label: orocrm.contact.first_name.label
                data_name: firstName
            last_name:
                label: orocrm.contact.last_name.label
                data_name: lastName
            primaryEmail:
                label: orocrm.contact.email.label
            primaryPhone:
                label: orocrm.contact.contactphone.phone.label
            countryName:
                label: orocrm.contact.contactaddress.country.label
            regionLabel:
                label: orocrm.contact.contactaddress.region.label
            addressPostalCode:
                label: orocrm.contact.contactaddress.postal_code.label
        properties:
            id: ~
        sorters:
            columns:
                hasContact: { data_name: hasContact }
            default:
                hasContact: DESC
        filters:
            columns:
                hasContact:
                    data_name: hasContact
                    type:      boolean
                first_name:
                    type: string
                    data_name: c.firstName
                last_name:
                    type: string
                    data_name: c.lastName
                primaryEmail:
                    type: string
                    data_name: email.email
                primaryPhone:
                    type: string
                    data_name: phone.phone
                countryName:
                    type: entity
                    data_name: address.country
                    enabled: false
                    options:
                        field_options:
                          class: OroAddressBundle:Country
                          property: name
                          query_builder: @orocrm_contact.contact.datagrid_helper->getCountryFilterQueryBuilder
                regionLabel:
                    type: string
                    data_name: regionLabel
                    enabled: false
                addressPostalCode:
                    type: string
                    data_name: addressPostalCode
                    enabled: false
        options:
            routerEnabled: false
            requireJSModules:
              - orodatagrid/js/datagrid/listener/column-form-listener
            columnListener:
                dataField: id
                columnName: hasContact
                selectors:
                    included: '#appendContacts'
                    excluded: '#removeContacts'
