parameters:
    orocrm_account.importexport.account_normalizer.class: OroCRM\Bundle\AccountBundle\ImportExport\Serializer\Normalizer\AccountNormalizer

services:
    orocrm_account.importexport.account_normalizer:
        class: %orocrm_account.importexport.account_normalizer.class%
        tags:
            - { name: oro_importexport.normalizer }
