oro_menu_config:
    items:
        customers_tab:
            label: Customers
            uri: '#'
            extras:
                position: 10

        account_list:
            label: orocrm.account.entity_plural_label
            route: orocrm_account_index
            extras:
                position: 5
                routes: ['orocrm_account_*']
                description: List of accounts

        shortcut_new_account:
            label: Create new account
            route: orocrm_account_create
            extras:
                description: Create new account instance
                isCustomAction: true

        shortcut_list_accounts:
            label: Show accounts list
            route: orocrm_account_index
            extras:
                description: List of accounts

    tree:
        application_menu:
            children:
                customers_tab:
                    children:
                        account_list: ~

        shortcuts:
            children:
                shortcut_new_account: ~
                shortcut_list_accounts: ~

oro_titles:
    orocrm_account_index: ~
    orocrm_account_view: %%account.name%%
    orocrm_account_create: Create Account
    orocrm_account_update: %%account.name%% - Edit
