parameters:
    orocrm_account.account.entity.class:            OroCRM\Bundle\AccountBundle\Entity\Account
    orocrm_account.type.account.class:              OroCRM\Bundle\AccountBundle\Form\Type\AccountType
    orocrm_account.handler.account.class:           OroCRM\Bundle\AccountBundle\Form\Handler\AccountHandler
    orocrm_account.form.type.account_select.class:  OroCRM\Bundle\AccountBundle\Form\Type\AccountSelectType

    orocrm_account.account.manager.api.class:       Oro\Bundle\SoapBundle\Entity\Manager\ApiEntityManager
    orocrm_account.type.account.api.class:          OroCRM\Bundle\AccountBundle\Form\Type\AccountApiType

services:
    orocrm_account.form.account:
        class:                                      Symfony\Component\Form\Form
        factory_method: createNamed
        factory_service: form.factory
        arguments: ["orocrm_account_form", "orocrm_account", null]

    orocrm_account.form.type.account:
        class:                                      %orocrm_account.type.account.class%
        arguments:
            - @router
            - @oro_locale.formatter.name
        tags:
            - { name: form.type, alias: orocrm_account }

    orocrm_account.form.handler.account:
        class:                                      %orocrm_account.handler.account.class%
        scope: request
        arguments:
            - @orocrm_account.form.account
            - @request
            - @doctrine.orm.entity_manager
        tags:
            - { name: oro_tag.tag_manager }

    # Form type
    orocrm_account.form.type.account_select:
        class:                                      %orocrm_account.form.type.account_select.class%
        arguments:
            - @doctrine.orm.entity_manager
        tags:
            - { name: form.type, alias: orocrm_account_select }

    # Account API
    orocrm_account.account.manager.api:
        class:                                      %orocrm_account.account.manager.api.class%
        arguments:
            - %orocrm_account.account.entity.class%
            - @doctrine.orm.entity_manager

    orocrm_account.form.type.account.api:
        class:                                      %orocrm_account.type.account.api.class%
        arguments:
            - @router
            - @oro_locale.formatter.name
        tags:
            - { name: form.type, alias: account }

    orocrm_account.form.account.api:
        class:                                      Symfony\Component\Form\Form
        factory_method: createNamed
        factory_service: form.factory
        arguments: ["account", "account", null]

    orocrm_account.form.handler.account.api:
        class:                                      %orocrm_account.handler.account.class%
        scope: request
        arguments:
            - @orocrm_account.form.account.api
            - @request
            - @doctrine.orm.entity_manager
        tags:
            - { name: oro_tag.tag_manager }

    orocrm_account.form.autocomplete.account.search_handler:
        parent: oro_form.autocomplete.search_handler
        arguments:
            - %orocrm_account.account.entity.class%
            - ["name"]
        tags:
            - { name: oro_form.autocomplete.search_handler, alias: accounts, acl_resource: orocrm_account_view }

    orocrm_account.event_listener.account_contacts_update_listener:
        class: %oro_datagrid.event_listener.base_orm_relation.class%
        arguments:
           - 'account'
           - @oro_datagrid.datagrid.request_params
        tags:
           - { name: kernel.event_listener, event: oro_datagrid.datagrid.build.after.account-contacts-update-grid, method: onBuildAfter }
