datagrid:
    calls-grid:
        source:
            type: orm
            acl_resource: orocrm_call_view
            query:
                select:
                    - call.id
                    - CONCAT(contact.firstName, CONCAT(' ', contact.lastName)) as contactName
                    - account.name as accountName
                    - call.subject
                    - CONCAT(CASE WHEN call.phoneNumber IS NOT NULL THEN call.phoneNumber ELSE contactPhone.phone END, '') as phone
                    - call.callDateTime as dateTime
                from:
                    - { table: %orocrm_call.call.entity.class%, alias: call }
                join:
                    left:
                        - { join: call.relatedContact, alias: contact }
                        - { join: call.contactPhoneNumber, alias: contactPhone }
                        - { join: call.relatedAccount, alias: account }
        columns:
            contactName:
                label: orocrm.call.datagrid.contact_name
            accountName:
                label: orocrm.call.datagrid.account_name
            subject:
                label: orocrm.call.subject.label
            phone:
                label: orocrm.call.phone_number.label
            dateTime:
                label: orocrm.call.call_date_time.label
                frontend_type: datetime
        filters:
            columns:
                contactName:
                    type: string
                    data_name: contactName
                accountName:
                    type: string
                    data_name: account.name
                subject:
                    type: string
                    data_name: call.subject
                phone:
                    type: string
                    data_name: phone
                dateTime:
                    type: datetime
                    data_name: call.callDateTime
        sorters:
            columns:
                contactName:
                    data_name: contactName
                accountName:
                    data_name: account.name
                subject:
                    data_name: call.subject
                phone:
                    data_name: phone
                dateTime:
                    data_name: call.callDateTime
            default:
                dateTime: DESC
        properties:
            id: ~
            update_link:
                type:       url
                route:      orocrm_call_update
                params:     [ id ]
            delete_link:
                type:       url
                route:      oro_api_delete_call
                params:     [ id ]
        actions:
            update:
                type:          navigate
                acl_resource:  orocrm_call_create
                label:         Update
                icon:          edit
                link:          update_link
                rowAction:     true
            delete:
                type:          delete
                acl_resource:  orocrm_call_delete
                label:         Delete
                icon:          trash
                link:          delete_link
                rowAction:     true
        options:
            entityHint: calls
            export: true

    widget-calls-grid:
        source:
            type: orm
            acl_resource: orocrm_call_view
            query:
                select:
                    - call.id
                    - contact.id as contactId
                    - CONCAT(contact.firstName, CONCAT(' ', contact.lastName)) as contactName
                    - account.id as accountId
                    - account.name as accountName
                    - call.subject
                    - CONCAT(CASE WHEN call.phoneNumber IS NOT NULL THEN call.phoneNumber ELSE contactPhone.phone END, '') as phone
                    - call.callDateTime as dateTime
                from:
                    - { table: %orocrm_call.call.entity.class%, alias: call }
                join:
                    left:
                        - { join: call.relatedContact, alias: contact }
                        - { join: call.contactPhoneNumber, alias: contactPhone }
                        - { join: call.relatedAccount, alias: account }
        columns:
            dateTime:
                label: orocrm.call.call_date_time.label
                frontend_type: datetime
            contactName:
                label: orocrm.call.datagrid.contact_name
                type: twig
                template: OroCRMCallBundle:Datagrid:Column/contactName.html.twig
                frontend_type: html
            accountName:
                label: orocrm.call.datagrid.account_name
                type: twig
                template: OroCRMCallBundle:Datagrid:Column/accountName.html.twig
                frontend_type: html
            subject:
                label: orocrm.call.subject.label
                type: twig
                template: OroCRMCallBundle:Datagrid:Column/subject.html.twig
                frontend_type: html
            phone:
                label: orocrm.call.phone_number.label
        filters:
            columns:
                contactName:
                    type: string
                    enabled: false
                    data_name: contactName
                accountName:
                    type: string
                    enabled: false
                    data_name: account.name
                subject:
                    type: string
                    data_name: call.subject
                phone:
                    type: string
                    data_name: phone
                dateTime:
                    type: datetime
                    data_name: call.callDateTime
        sorters:
            columns:
                contactName:
                    data_name: contactName
                accountName:
                    data_name: account.name
                subject:
                    data_name: call.subject
                phone:
                    data_name: phone
                dateTime:
                    data_name: call.callDateTime
            default:
                dateTime: DESC
        properties:
            id: ~
            contactId: ~
            accountId: ~
        options:
            entityHint: calls

    dashboard-recent-calls-grid:
        options:
            entityHint: call
        source:
            type: orm
            acl_resource: orocrm_call_view
            query:
                select:
                    - call.id
                    - CONCAT(contact.firstName, CONCAT(' ', contact.lastName)) as contactName
                    - contact.id as contactId
                    - account.name as accountName
                    - call.subject
                    - CONCAT(CASE WHEN call.phoneNumber IS NOT NULL THEN call.phoneNumber ELSE contactPhone.phone END, '') as phone
                    - call.callDateTime as dateTime
                    - directionType.name as callDirection
                from:
                    - { table: %orocrm_call.call.entity.class%, alias: call }
                join:
                    left:
                        - { join: call.relatedContact, alias: contact }
                        - { join: call.contactPhoneNumber, alias: contactPhone }
                        - { join: call.relatedAccount, alias: account }
                        - { join: call.direction, alias: directionType }
                    inner:
                        - { join: call.owner, alias: ownerUser }
                where:
                    and:
                      - ownerUser.id = @oro_security.security_facade->getLoggedUserId
        columns:
            callDirection:
                type: twig
                label: ~
                frontend_type: html
                template: OroCRMCallBundle:Datagrid:Column/direction.html.twig
            dateTime:
                label: orocrm.call.datagrid.date_time
                frontend_type: datetime
            contactName:
                type: twig
                label: orocrm.call.datagrid.contact_name
                frontend_type: html
                template: OroCRMCallBundle:Datagrid:Column/contactName.html.twig
            subject:
                type: twig
                label: orocrm.call.subject.label
                frontend_type: html
                template: OroCRMCallBundle:Datagrid:Column/subject.html.twig
            phone:
                label: orocrm.call.phone_number.label
        sorters:
            columns:
                dateTime:
                    data_name: call.callDateTime
            default:
                dateTime: DESC
        options:
            toolbarOptions:
                hide: true
                pageSize:
                    items: [10]
                    default_per_page: 10
