oro_menu_config:
    items:
        sales_tab:
            label: Sales
            uri:   '#'
            extras:
                position: 20

        lead_list:
            label: orocrm.sales.lead.entity_plural_label
            route: orocrm_sales_lead_index
            extras:
                position:    20
                routes:      ['/^orocrm_sales_lead/']
                description: List of leads

        opportunity_list:
            label: orocrm.sales.opportunity.entity_plural_label
            route: orocrm_sales_opportunity_index
            extras:
                position:    30
                routes:      ['/^orocrm_sales_opportunity/']
                description: List of opportunities

        sales_salesfunnel_list:
            label: orocrm.sales.salesfunnel.entity_plural_label
            route: orocrm_sales_salesfunnel_index
            extras:
                position:    10
                routes:      ['/^orocrm_sales_salesfunnel/']
                description: List of sales funnels

        shortcut_list_leads:
            label: Show leads list
            route: orocrm_sales_lead_index
            extras:
                description: List of leads

        shortcut_list_opportunities:
            label: Show opportunities list
            route: orocrm_sales_opportunity_index
            extras:
                description: List of opportunities

        shortcut_new_lead:
            label: Create new lead
            route: orocrm_sales_lead_create
            extras:
                description: Create new lead
                isCustomAction: true

        shortcut_new_opportunity:
            label: Create new opportunity
            route: orocrm_sales_opportunity_create
            extras:
                description: Create new opportunity
                isCustomAction: true

        orocrm_sales_account_leads_tab:
            label: orocrm.sales.widgets.leads
            extras:
                position: 10
                widgetRoute: orocrm_sales_widget_account_leads
                widgetAcl: orocrm_sales_lead_view

        orocrm_sales_account_opportunities_tab:
            label: orocrm.sales.widgets.opportunities
            extras:
                position: 20
                widgetAcl: orocrm_sales_opportunity_view
                widgetRoute: orocrm_sales_widget_account_opportunities

    tree:
        application_menu:
            children:
                sales_tab:
                    children:
                        sales_salesfunnel_list: ~
                        lead_list: ~
                        opportunity_list: ~
        shortcuts:
            children:
                shortcut_list_leads: ~
                shortcut_list_opportunities: ~
                shortcut_new_lead: ~
                shortcut_new_opportunity: ~

        account_sales_tab_panel:
            children:
                orocrm_sales_account_leads_tab: ~
                orocrm_sales_account_opportunities_tab: ~
                orocrm_magento_account_orders_tab: ~

oro_titles:
    orocrm_sales_opportunity_index: ~
    orocrm_sales_opportunity_view: %%opportunity.name%%
    orocrm_sales_opportunity_create: Create Opportunity
    orocrm_sales_opportunity_update: %%opportunity.name%% - Edit

    orocrm_sales_lead_index: ~
    orocrm_sales_lead_view: %%lead.name%%
    orocrm_sales_lead_create: Create Lead
    orocrm_sales_lead_update: %%lead.name%% - Edit

    orocrm_sales_salesfunnel_index: ~
    orocrm_sales_salesfunnel_view: %%sales_funnel%%
    orocrm_sales_salesfunnel_create: Create Sales Activity
    orocrm_sales_salesfunnel_update: %%sales_funnel%% - Edit
