connector:
    name: oro_importexport
    jobs:
        # Customer import job
        # sweettooth_customer_import:
        #     title: "Entity Import from Sweet Tooth REST API"
        #     type: import
        #     steps:
        #         import:
        #             title:     import
        #             services:
        #                 reader:    sweettooth_channel.sweettooth.customer_connector
        #                 processor: oro_importexport.processor.import_delegate
        #                 writer:    oro_integration.writer.persistent_batch_writer
        #             parameters:
        #                 batch_size: 100
