oro_crm_magento_bundle:
    resource:     "@OroCRMMagentoBundle/Controller"
    type:         annotation
    prefix:       /magento

oro_crm_magento_dashboard:
    resource:     "@OroCRMMagentoBundle/Controller/Dashboard"
    type:         annotation
    prefix:       /dashboard
