orocrm_account_bundle:
    resource:     "@OroCRMAccountBundle/Controller"
    type:         annotation
    prefix:       /account

orocrm_account_api_account:
    resource:     "@OroCRMAccountBundle/Controller/Api/Rest/AccountController.php"
    type:         rest
    prefix:       api/rest/{version}/
    requirements:
        version:  latest|v1
    defaults:
        version:  latest
