OroCRM\Bundle\MagentoBundle\Entity\MagentoSoapTransport:
    properties:
        wsdlUrl:
          - NotBlank: ~
        apiUser:
          - NotBlank: ~
        syncStartDate:
          - NotBlank: ~
        websiteId:
          - NotBlank: ~
