orocrm_sales_bundle:
    resource: "@OroCRMSalesBundle/Controller"
    type:     annotation

orocrm_sales_dashboard:
    resource:     "@OroCRMSalesBundle/Controller/Dashboard"
    type:         annotation
    prefix:       /dashboard

orocrm_sales_bundle_api:
    resource: "@OroCRMSalesBundle/Resources/config/oro/routing_api.yml"
    type: rest
    prefix: api/rest/{version}
    requirements:
        version:  latest|v1
    defaults:
        version:  latest
