oro_menu_config:
    items:
        task_list:
            label: orocrm.task.entity_plural_label
            route: orocrm_task_index
            extras:
                position: 10
                routes: ['orocrm_task_*']
                description: List of tasks

        orocrm_task_account_tasks_tab:
            label: orocrm.task.widgets.account_tasks
            extras:
                position: 10
                widgetAcl: orocrm_task_view
                widgetRoute: orocrm_task_widget_account_tasks

    tree:
        application_menu:
            children:
                activities_tab:
                    children:
                        task_list: ~

        account_activity_tab_panel:
            children:
                orocrm_task_account_tasks_tab: ~

oro_titles:
    orocrm_task_index: ~
    orocrm_task_view: %%entity.subject%%
    orocrm_task_create: Create %%entityName%%
    orocrm_task_update: %%entity.subject%% - Edit
