datagrid:

    # TODO: Move to SweetToothContactBundle after creating SweetToothContactOverrideBundle
    widget-points-history-grid:
        source:
            type: points_history
            acl_resource: orocrm_call_view
        columns:
            description:
                label: "Description"
            points_change:
                label: "Points"
            created:
                label: "Created"
                frontend_type: datetime
        sorters:
            columns:
                description:
                    data_name: description
                points_change:
                    data_name: points_change
                created:
                    data_name: created
            default:
                created: DESC
        properties:
            id: ~
            contactId: ~
        options:
            entityHint: points history

