datagrid:
    dashboard-my-contacts-activity-grid:
        source:
            type: orm
            acl_resource: orocrm_contact_view
            query:
                select:
                    - c.id
                    - CONCAT(c.firstName, CONCAT(' ', c.lastName)) as contactName
                    - email.email as primaryEmail
                    - phone.phone as primaryPhone
                    - max(history.visitedAt) as visitDate
                from:
                    - { table: %orocrm_contact.entity.class%, alias: c }
                join:
                    left:
                        - { join: c.emails, alias: email, conditionType: WITH, condition: 'email.primary = true' }
                        - { join: c.phones, alias: phone, conditionType: WITH, condition: 'phone.primary = true' }
                    inner:
                        -
                            join: Oro\Bundle\NavigationBundle\Entity\NavigationHistoryItem
                            alias: history
                            conditionType: WITH
                            condition: "c.id = substring(history.url, locate('/', history.url, locate('/contact/', history.url) + 9) + 1)"
                where:
                    and:
                      - locate('/contact/', history.url) <> 0
                      - history.user = @oro_security.security_facade->getLoggedUserId
                groupBy:  c.id, contactName, primaryEmail, primaryPhone
        sorters:
            visitDate: { history.: %oro_datagrid.extension.orm_sorter.class%::DIRECTION_DESC }
        columns:
            contactName:
                type: twig
                label: orocrm.contact.datagrid.contact_name
                frontend_type: html
                template: OroCRMContactBundle:Contact:Datagrid/Property/contactName.html.twig
            primaryEmail:
                label: orocrm.contact.email.label
            primaryPhone:
                label: orocrm.contact.contactphone.phone.label
        options:
            entityHint: contact
            toolbarOptions:
                hide: true
                pageSize:
                    items: [10]
                    default_per_page: 10

    # contact groups grid, shown on orocrm_contact_group_index
    contact-groups-grid:
        source:
            type: orm
            acl_resource: orocrm_contact_group_view
            query:
                select:
                    - g.id
                    - g.label
                from:
                  - { table: %orocrm_contact.group.entity.class%, alias: g }
        columns:
            label:
                label: orocrm.contact.group.label.label
        properties:
            id: ~
            update_link:
                type:       url
                route:      orocrm_contact_group_update
                params:     [ id ]
            delete_link:
                type:       url
                route:      oro_api_delete_contactgroup
                params:     [ id ]
        sorters:
            columns:
                label:
                    data_name: g.label
        filters:
            columns:
                label:
                    type:      string
                    data_name: g.label
        actions:
            update:
                type:          navigate
                acl_resource:  orocrm_contact_group_update
                label:         Update
                icon:          edit
                link:          update_link
                rowAction:     true
            delete:
                type:          delete
                acl_resource:  orocrm_contact_group_delete
                label:         Delete
                icon:          trash
                link:          delete_link
        options:
            entityHint: group

    # contacts assigned to group, shown on orocrm_contact_group_update route
    contact-group-contacts-grid:
        source:
            type: orm
            acl_resource: orocrm_contact_view
            query:
                select:
                    - c.id
                    - c.firstName
                    - c.lastName
                    - >
                      (CASE WHEN (:group IS NOT NULL) THEN
                        CASE WHEN (:group MEMBER OF c.groups OR c.id IN (:data_in)) AND c.id NOT IN (:data_not_in)
                        THEN true ELSE false END
                      ELSE
                        CASE WHEN c.id IN (:data_in) AND c.id NOT IN (:data_not_in)
                        THEN true ELSE false END
                      END) as hasGroup
                from:
                    - { table: %orocrm_contact.entity.class%, alias: c }
        columns:
            hasGroup:
                label: Has group
                editable: true
                frontend_type: boolean
            firstName:
                label: orocrm.contact.first_name.label
            lastName:
                label: orocrm.contact.last_name.label
        properties:
            id: ~
        filters:
            columns:
                hasGroup:
                    data_name: hasGroup
                    type:  boolean
                firstName:
                    type: string
                    data_name: c.firstName
                lastName:
                    type: string
                    data_name: c.firstName
        sorters:
            columns:
                hasGroup:
                    data_name: hasGroup
                firstName:
                    data_name: c.firstName
                lastName:
                    data_name: c.lastName
            default: { hasGroup: %oro_datagrid.extension.orm_sorter.class%::DIRECTION_DESC }
        options:
            entityHint: contact
            requireJSModules:
                - orodatagrid/js/datagrid/listener/column-form-listener
            columnListener:
                dataField: id
                columnName: hasGroup
                selectors:
                    included: '#groupAppendContacts'
                    excluded: '#groupRemoveContacts'

    # contacts main grid show on  orocrm_contact_index route
    contacts-grid:
        extended_entity_name: %orocrm_contact.entity.class%
        source:
            type: orm
            acl_resource: orocrm_contact_view
            query:
                select:
                    # selects full entity because group labels should be taken from object
                    - c
                    - contactSource.label as contactSourceLabel
                    - email.email as primaryEmail
                    - phone.phone as primaryPhone
                    - CONCAT(CASE WHEN address.regionText IS NOT NULL THEN address.regionText ELSE region.name END, '') as regionLabel
                    - country.name as countryName
                    - address.postalCode as addressPostalCode
                    - contactGroup
                from:
                    - { table: %orocrm_contact.entity.class%, alias: c }
                join:
                    left:
                        - { join: c.addresses, alias: address, conditionType: WITH, condition: 'address.primary = true' }
                        - { join: c.emails, alias: email, conditionType: WITH, condition: 'email.primary = true' }
                        - { join: c.phones, alias: phone, conditionType: WITH, condition: 'phone.primary = true' }
                        - { join: c.groups, alias: contactGroup }
                        - { join: c.source, alias: contactSource }
                        - { join: address.country, alias: country }
                        - { join: address.region, alias: region }
            hints:
                - { name: HINT_CUSTOM_OUTPUT_WALKER, value: %oro_translation.translation_walker.class%}
        columns:
            firstName:
                label: orocrm.contact.first_name.label
            lastName:
                label: orocrm.contact.last_name.label
            primaryEmail:
                label: orocrm.contact.email.label
            primaryPhone:
                label: orocrm.contact.contactphone.phone.label
            groupLabelsAsString:
                label: orocrm.contact.groups.label
            contactSourceLabel:
                label: orocrm.contact.source.label
            countryName:
                label: orocrm.contact.contactaddress.country.label
            regionLabel:
                label: orocrm.contact.contactaddress.region.label
            addressPostalCode:
                label: orocrm.contact.contactaddress.postal_code.label
            createdAt:
                label: orocrm.contact.created_at.label
                frontend_type: datetime
            updatedAt:
                label: orocrm.contact.updated_at.label
                frontend_type: datetime
        properties:
            id: ~
            view_link:
                type:       url
                route:      orocrm_contact_view
                params:     [ id ]
            update_link:
                type:       url
                route:      orocrm_contact_update
                params:     [ id ]
            delete_link:
                type:       url
                route:      oro_api_delete_contact
                params:     [ id ]
        sorters:
            columns:
                firstName:
                    data_name: c.firstName
                lastName:
                    data_name: c.lastName
                primaryEmail:
                    data_name: email.email
                primaryPhone:
                    data_name: phone.phone
                groupLabelsAsString:
                    data_name: contactGroup.label
                contactSourceLabel:
                    data_name: contactSource.label
                countryName:
                    data_name: country.name
                regionLabel:
                    data_name: regionLabel
                addressPostalCode:
                    data_name: address.postalCode
                createdAt:
                    data_name: c.createdAt
                updatedAt:
                    data_name: c.updatedAt
            default:
                firstName: %oro_datagrid.extension.orm_sorter.class%::DIRECTION_ASC
                lastName:  %oro_datagrid.extension.orm_sorter.class%::DIRECTION_ASC
        filters:
            columns:
                firstName:
                    type: string
                    data_name: c.firstName
                lastName:
                    type: string
                    data_name: c.lastName
                primaryEmail:
                    type: string
                    data_name: email.email
                primaryPhone:
                    type: string
                    data_name: phone.phone
                groupLabelsAsString:
                    type: entity
                    data_name: contactGroup.id
                    enabled: false
                    options:
                        field_options:
                            class: OroCRMContactBundle:Group
                            property: label
                contactSourceLabel:
                    type: entity
                    data_name: contactSource.name
                    enabled: false
                    options:
                        field_options:
                            class: OroCRMContactBundle:Source
                            property: label
                countryName:
                    type: entity
                    data_name: address.country
                    enabled: false
                    options:
                        field_options:
                          class: OroAddressBundle:Country
                          property: name
                          query_builder: @orocrm_contact.contact.datagrid_helper->getCountryFilterQueryBuilder
                regionLabel:
                    type: string
                    data_name: regionLabel
                    enabled: false
                addressPostalCode:
                    type: string
                    data_name: addressPostalCode
                    enabled: false
                createdAt:
                    type:      datetime
                    data_name: c.createdAt
                updatedAt:
                    type:      datetime
                    data_name: c.updatedAt
                    enabled: false
        actions:
            view:
                type: navigate
                acl_resource: orocrm_contact_view
                label: orocrm.contact.datagrid.view
                icon: user
                link: view_link
                rowAction: true
            update:
                type: navigate
                acl_resource: orocrm_contact_update
                label: orocrm.contact.datagrid.update
                icon: edit
                link: update_link
            delete:
                type: delete
                acl_resource: orocrm_contact_delete
                label: orocrm.contact.datagrid.delete
                icon: trash
                link: delete_link
        mass_actions:
            delete:
                type: delete
                entity_name: %orocrm_contact.entity.class%
                data_identifier: c.id
                acl_resource: orocrm_contact_delete
                label: orocrm.contact.datagrid.delete
                icon: trash
        options:
            entityHint: contact
            export: true

    # contact email datagrid
    contacts-email-grid:
        extends: email-grid
        source:
            query:
                where:
                    and:
                        - a.email IN (:email_addresses)

    # assigned accounts grid
    contact-accounts-grid:
        source:
            type: orm
            acl_resource: orocrm_contact_update
            query:
                select:
                    - a.id
                    - a.name
                    - a.createdAt
                    - a.updatedAt
                    - defaultContact.firstName as contactFirstName
                    - defaultContact.lastName as contactLastName
                    - defaultContactEmail.email as contactEmail
                    - defaultContactPhone.phone as contactPhone
                    - CONCAT(accountOwner.firstName, CONCAT(' ', accountOwner.lastName)) as ownerName
                    - >
                      (CASE WHEN (:contact IS NOT NULL) THEN
                        CASE WHEN (:contact MEMBER OF a.contacts OR a.id IN (:data_in)) AND a.id NOT IN (:data_not_in)
                        THEN true ELSE false END
                      ELSE
                        CASE WHEN a.id IN (:data_in) AND a.id NOT IN (:data_not_in)
                        THEN true ELSE false END
                      END) as hasContact
                from:
                    - { table: OroCRMAccountBundle:Account, alias: a }
                join:
                    left:
                        - { join: a.defaultContact, alias: defaultContact }
                        - { join: defaultContact.emails, alias: defaultContactEmail, conditionType: 'WITH', condition: 'defaultContactEmail.primary = true' }
                        - { join: defaultContact.phones, alias: defaultContactPhone, conditionType: 'WITH', condition: 'defaultContactPhone.primary = true' }
                        - { join: a.owner, alias: accountOwner }
        columns:
            hasContact:
                label:   Assigned
                editable: true
                frontend_type: boolean
            name:
                label:   orocrm.account.name.label
            contactFirstName:
                label:   orocrm.contact.first_name.label
            contactLastName:
                label:   orocrm.contact.last_name.label
            contactEmail:
                label:   orocrm.contact.contactemail.email.label
            contactPhone:
                label:   orocrm.contact.contactphone.phone.label
            ownerName:
                label:   orocrm.contact.owner.label
            createdAt:
                label:   orocrm.contact.created_at.label
                frontend_type: datetime
            updatedAt:
                label:   orocrm.contact.updated_at.label
                frontend_type: datetime
        sorters:
            columns:
                hasContact:        { data_name: hasContact }
                name:              { data_name: a.name }
                contactFirstName:  { data_name: contactFirstName }
                contactLastName:   { data_name: contactLastName }
                contactEmail:      { data_name: contactEmail }
                contactPhone:      { data_name: contactPhone }
                ownerName:         { data_name: ownerName }
                createdAt:         { data_name: a.createdAt }
                updatedAt:         { data_name: a.updatedAt }
            default: { hasContact: %oro_datagrid.extension.orm_sorter.class%::DIRECTION_DESC }
        filters:
            columns:
                hasContact:
                    data_name: hasContact
                    type:      boolean
                name:
                    type:      string
                    data_name: a.name
                contactFirstName:
                    type:      string
                    data_name: contactFirstName
                contactLastName:
                    type:      string
                    data_name: contactLastName
                contactEmail:
                    type:      string
                    data_name: contactEmail
                contactPhone:
                    type:      string
                    data_name: contactPhone
                ownerName:
                    type:      string
                    data_name: ownerName
                createdAt:
                    type:      datetime
                    data_name: a.createdAt
                updatedAt:
                    type:      datetime
                    data_name: a.updatedAt
        properties:
            id: ~
        options:
            entityHint: account
            requireJSModules:
              - orodatagrid/js/datagrid/listener/column-form-listener
            columnListener:
                dataField: id
                columnName: hasContact
                selectors:
                    included: '#appendAccounts'
                    excluded: '#removeAccounts'
