placeholders:
    view_content_data_additional_information:
        items:
            sweettooth_contact_points_balance: ~
            sweettooth_contact_points_history: ~

items:
    sweettooth_contact_points_balance:
        template: SweetToothContactBundle:Loyalty:contactPointsBalance.html.twig
        attribute_instance_of: [entity, %orocrm_contact.entity.class%]

    sweettooth_contact_points_history:
        template: SweetToothContactBundle:Loyalty:contactPointsHistory.html.twig
        attribute_instance_of: [entity, %orocrm_contact.entity.class%]
